version: "3.4"

services:
  postgres:
    container_name: hackmanv7
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: hackman
      POSTGRES_PASSWORD: hackman
volumes:
  postgres_data:
